<a href="https://colab.research.google.com/github/Mounika2419/Banking-Transaction/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
import pandas as pd

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
import pandas as pd
df=pd.read_csv("/content/iris.data",head=none)

In [ ]:
#accesind dataset
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [ ]:
#accesind 1st 5 columns data
df.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [ ]:
#accesing last columns data
df.tail()

     5.1  3.5  1.4  0.2     Iris-setosa
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

In [ ]:
#giving name to header columns
df.columns = ["sepal_length","sepal_width","petal_length","petal_width","iris"]
df.head()

   sepal_length  sepal_width  petal_length  petal_width         iris
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

In [ ]:
#to represent number of rowsand columns
df.shape

(149, 5)

In [ ]:
#extracting column name of the dataset
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'iris'], dtype='object')

In [ ]:
#accesind single column data
df["sepal_width"]

0      3.0
1      3.2
2      3.1
3      3.6
4      3.9
      ...
144    3.0
145    2.5
146    3.0
147    3.4
148    3.0
Name: sepal_width, Length: 149, dtype: float64

In [ ]:
#accesing two columns data
df[["sepal_length","sepal_width"]]

     sepal_length  sepal_width
0             4.9          3.0
1             4.7          3.2
2             4.6          3.1
3             5.0          3.6
4             5.4          3.9
..            ...          ...
144           6.7          3.0
145           6.3          2.5
146           6.5          3.0
147           6.2          3.4
148           5.9          3.0

[149 rows x 2 columns]

In [ ]:
#index location
df.iloc[0]

sepal_length            4.9
sepal_width             3.0
petal_length            1.4
petal_width             0.2
iris            Iris-setosa
Name: 0, dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  149 non-null    float64
 1   sepal_width   149 non-null    float64
 2   petal_length  149 non-null    float64
 3   petal_width   149 non-null    float64
 4   iris          149 non-null    object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB

In [ ]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    149.000000   149.000000    149.000000   149.000000
mean       5.848322     3.051007      3.774497     1.205369
std        0.828594     0.433499      1.759651     0.761292
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.400000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
#to identify the missing value
#true =null value
#false=non null
df.isnull()

     sepal_length  sepal_width  petal_length  petal_width   iris
0           False        False         False        False  False
1           False        False         False        False  False
2           False        False         False        False  False
3           False        False         False        False  False
4           False        False         False        False  False
..            ...          ...           ...          ...    ...
144         False        False         False        False  False
145         False        False         False        False  False
146         False        False         False        False  False
147         False        False         False        False  False
148         False        False         False        False  False

[149 rows x 5 columns]

In [ ]:
df.dropna()

     sepal_length  sepal_width  petal_length  petal_width            iris
0             4.9          3.0           1.4          0.2     Iris-setosa
1             4.7          3.2           1.3          0.2     Iris-setosa
2             4.6          3.1           1.5          0.2     Iris-setosa
3             5.0          3.6           1.4          0.2     Iris-setosa
4             5.4          3.9           1.7          0.4     Iris-setosa
..            ...          ...           ...          ...             ...
144           6.7          3.0           5.2          2.3  Iris-virginica
145           6.3          2.5           5.0          1.9  Iris-virginica
146           6.5          3.0           5.2          2.0  Iris-virginica
147           6.2          3.4           5.4          2.3  Iris-virginica
148           5.9          3.0           5.1          1.8  Iris-virginica

[149 rows x 5 columns]

In [ ]:
df.fillna(1)

     sepal_length  sepal_width  petal_length  petal_width            iris
0             4.9          3.0           1.4          0.2     Iris-setosa
1             4.7          3.2           1.3          0.2     Iris-setosa
2             4.6          3.1           1.5          0.2     Iris-setosa
3             5.0          3.6           1.4          0.2     Iris-setosa
4             5.4          3.9           1.7          0.4     Iris-setosa
..            ...          ...           ...          ...             ...
144           6.7          3.0           5.2          2.3  Iris-virginica
145           6.3          2.5           5.0          1.9  Iris-virginica
146           6.5          3.0           5.2          2.0  Iris-virginica
147           6.2          3.4           5.4          2.3  Iris-virginica
148           5.9          3.0           5.1          1.8  Iris-virginica

[149 rows x 5 columns]